### ISSUE TITLE
URL for downloading open Dutch CML dataset is outdated

### ISSUE THREAD

**Issue by cchwala** [OpenSenseAction/OPENSENSE_sandbox#48]
The URL in the [data dowloader for the Dutch CML dataset](https://github.com/OpenSenseAction/OPENSENSE_sandbox/blob/adae1ba0fba0c776751755d2a1c959669d6d52e0/notebooks/opensense_data_downloader_and_transformer.py#L139) is outdated, probably because the data portal https://data.4tu.nl was updated.

**Comment by cchwala** [comment]
The new URL for the `data.zip` file from the dataset website https://data.4tu.nl/datasets/7a692e36-c32f-4916-813b-c62d2566e8d8 should be 
```
https://data.4tu.nl/file/7a692e36-c32f-4916-813b-c62d2566e8d8/163c5cc1-5b72-40e7-9dbf-b30b690fe260
```

**Comment by overeem11** [comment]
Note that version 2 of the dataset is now available. Also note that the old URL now works again, so we could keep this: https://data.4tu.nl/datasets/7a692e36-c32f-4916-813b-c62d2566e8d8 In case you really want to point to the zip file directly instead of the website describing the dataset, you could use https://data.4tu.nl/file/7a692e36-c32f-4916-813b-c62d2566e8d8/e13a512f-a9af-4cdf-97be-aa0e474a3dc0 (in any case do not use https://data.4tu.nl/file/7a692e36-c32f-4916-813b-c62d2566e8d8/163c5cc1-5b72-40e7-9dbf-b30b690fe260, because it points to version 1, which has partly an erroneous time stamp).
